packages:
  - packages/*

allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false

link-workspace-packages: true

minimumReleaseAgeExclude:
  - three
  - '@tanstack/charts'
  - tanstack-router-ga4
  - yargs-file-commands
  - '@vitest/browser-playwright'
  - '@vitest/browser'
  - '@vitest/coverage-v8'
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/spy'
  - '@vitest/ui'
  - '@vitest/utils'
  - vitest
