packages:
  - packages/*

allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false

link-workspace-packages: true

minimumReleaseAgeExclude:
  - three
  - '@tanstack/charts'
  - tanstack-router-ga4
  - yargs-file-commands
