packages:
  - packages/*

allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false

link-workspace-packages: true

minimumReleaseAgeExclude:
  - three@0.186.0
  - '@tanstack/charts@0.16.2'
