name: Deploy demo to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy demo to Cloud Run
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: three-ntc
      dockerfile: packages/website/Dockerfile
      context: .
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
